version: 2

project_name: binman

before:
  hooks:
    - go mod tidy

builds:
  - id: binman
    main: .
    binary: binman
    env:
      - CGO_ENABLED=0
    goos: [darwin, linux]
    goarch: [arm64, amd64]
    ldflags:
      - -s -w -X github.com/thaitrn/binman/cmd.Version={{.Version}}

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{- title .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: checksums.txt

release:
  github:
    owner: thaitrn
    name: binman

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
